safe: false

title: Cryptom
email: ola@algorithmia.tech
description: >- # this means to ignore newlines until "baseurl:"
  For all your analytical needs.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://algorithmias.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: algorithmias
github_username:  algorithmias
defaults:
  - scope:
      path: ""
      type: moments
    values:
      permalink: /moments.json
  - scope:
      path: ""
      type: signals
    values:
      permalink: /signals.json
  - scope:
      path: ""
      type: trendlines
    values:
      permalink: /trendlines.json

collections:
  moments:
    output: true
    permalink: /:collection/:path
    files:
      - moments/**/* 
  signals:
    output: true
    permalink: /:collection/:path
    files:
      - signals/**/*
  trendlines:
    output: true
    permalink: /:collection/:path
    files:
      - trendlines/**/*
      
# Build settings
theme: minima
