safe: false

title: Cryptom

email: ola@algorithmia.tech

description: >- 
  For all your analytical needs.

url: "https://algorithmias.github.io"

twitter_username: algorithmias
github_username:  algorithmias

collections:
  moments:
    output: true
    permalink: /:collection/:path
    files:
      - moments/**/* 
  signals:
    output: true
    permalink: /:collection/:path
    files:
      - signals/**/*
  trendlines:
    output: true
    permalink: /:collection/:path
    files:
      - trendlines/**/*
  root:
    output: true
    permalink: /:collection/:path
    files:
      - _data/*

defaults:
  - scope:
      path: "moments.json"
    values:
      permalink: /moments.json
  - scope:
      path: "signals.json"
    values:
      permalink: /signals.json
  - scope:
      path: "trendlines.json"
    values:
      permalink: /trendlines.json

# permalink: /moments.json
# permalink: /signals.json
# permalink: /trendlines.json
      
# Build settings
theme: minima
